#ifndef STATUS_H
#define STATUS_H

#define STATUS_OK					0
#define STATUS_ERROR				1
#define STATUS_INCORRECT_ARGUMENT	2
#define STATUS_ALLOCATION_ERROR		3
#define STATUS_INCORRECT_COLOR		4

#endif	// STATUS_H